### ISSUE TITLE
Right-Clicking turns a "special" block into a "normal" block

### ISSUE THREAD

**Issue by Wertzui123** [JavierLeon9966/ExtendedBlocks#10]
While testing out this plugin, I noticed that right-clicking turns a block with let's say id 526 (ancient debris) into 14 (gold ore).
This also happens with other blocks above 256.

**Comment by Wertzui123** [comment]
It also shows the wrong block break particles.

**Comment by JavierLeon9966** [comment]
Well that means you registered the new block in the wrong way. Lemme see your code

**Comment by Wertzui123** [comment]
```php
<?php

namespace Wertzui123\EBT;

use pocketmine\block\Block;
use JavierLeon9966\ExtendedBlocks\block\PlaceholderTrait;

class AncientDebris extends Block
{

    use PlaceholderTrait;

}
```

```php
BlockFactory::registerBlock(new AncientDebris(527));
```

**Comment by Mohagames205** [comment]
According to the documentation you also need to add  `protected $id = 527;` in the class. I hope it works!

source: https://github.com/JavierLeon9966/ExtendedBlocks#format-you-must-use

**Comment by Wertzui123** [comment]
That does not work either.

**Comment by JavierLeon9966** [comment]
What version are you using?

**Comment by Wertzui123** [comment]
The latest poggit release.

**Comment by JavierLeon9966** [comment]
You must do the
```php
BlockFactory::registerBlock(new AncientDebris(527));
```
Inside a class otherwise won’t register at all and also register in item form like:
```php
ItemFactory::registerItem(new ItemBlock(527, 0, 255 - 527));
```

**Comment by Wertzui123** [comment]
> Inside a class

I am of course doing it inside my main class

> ItemFactory::registerItem(new ItemBlock(527, 0, 255 - 527));

I am not using items, I used level->setBlock for testing

**Comment by JavierLeon9966** [comment]
The only way that would work is:
```php
$level->setBlock($pos, new Placeholder($block), true, true);
```

**Comment by Wertzui123** [comment]
> 
> 
> The only way that would work is:
> 
> ```php
> $level->setBlock($pos, new Placeholder($block), true, true);
> ```

![grafik](https://user-images.githubusercontent.com/46199283/110999278-6e07f580-8380-11eb-8d15-26782737d869.png)
That produces this Reserved6 block.

**Comment by JavierLeon9966** [comment]
Is there any errors at console or is the plugin enabled correctly?

**Comment by JavierLeon9966** [comment]
It seems that you implement wrong the block and when I registered a block myself everything works perfectly, so this issue will be closed as invalid. If you experience any others issues or have a suggestion feel free to create a new issue.

**Comment by Wertzui123** [comment]
> Is there any errors at console or is the plugin enabled correctly?

I think it does.

> It seems that you implement wrong the block and when I registered a block myself everything works perfectly, so this issue will be closed as invalid. If you experience any others issues or have a suggestion feel free to create a new issue.

Ok, thanks for your help anyway. I would rather mark this issue as not reproducible as it seems to be a problem with the plugin for me and we didn't find a solution (yet).
