### ISSUE TITLE
My plugin is not work

### ISSUE THREAD

**Issue by mentagess** [JavierLeon9966/ExtendedBlocks#14]
hello I can not create a block with a lower id with your plugin while I am what is marked in the readme.md

**Comment by JavierLeon9966** [comment]
Show me your main class and block class

**Comment by mentagess** [comment]
<?php

namespace Mentagess\Block;

use pocketmine\block\BlockFactory;
use pocketmine\item\ItemBlock;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase{
  
  public function onLoad(){
    BlockFactory::registerBlock($block);
    ItemFactory::addCreativeItem(ItemFactory::get(255 - $block->getId()));
  }
}
here I have this but I do not know what to put in my variable.

**Comment by mentagess** [comment]
`<?php

namespace Mentagess\Block;

use pocketmine\block\BlockFactory;
use pocketmine\item\ItemBlock;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase{
  
  public function onLoad(){
    BlockFactory::registerBlock($block);
    ItemFactory::addCreativeItem(ItemFactory::get(255 - $block->getId()));
  }
}`

**Comment by supercrafter333** [comment]
Don't use pocketmines ItemFactory! Use the ItemFactory of this plugin.

**Comment by mentagess** [comment]
> Don't use pocketmines ItemFactory! Use the ItemFactory of this plugin.

I use it but its making me a mistake.

**Comment by mentagess** [comment]
there is still an error here here:

`<?php

namespace Mentagess\Block;

use pocketmine\item\ItemBlock;
use JavierLeon9966\ExtendedBlocks\item\ItemFactory;
use pocketmine\plugin\PluginBase;
use pocketmine\block\BlockFactory;
use pocketmine\block\Block;

class Main extends PluginBase{
  
    public function onLoad(){
  BlockFactory::registerBlock(new Block(526, 0, "Blocktest"));
  ItemFactory::addCreativeItem(ItemFactory::get(255 - 526)); 
    }
 }`

**Comment by mentagess** [comment]
Here is the error
[Click here](https://discord.com/channels/@me/719315107632382083/823206713636945980)
Or 
`RuntimeExeption: "Index invalid or out range" (EXEPTION) in "pmsrc/src/pocketmine/block/BlockFactory" at line 428`

**Comment by JavierLeon9966** [comment]
1. You must do the stuff in the onEnable method
2. You need to use a block class that uses the `PlaceholderTrait`

**Comment by mentagess** [comment]
Thank my problem is solved it works.
