### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by supercrafter333** [JavierLeon9966/ExtendedBlocks#16]
Can you add support for stairs, fences and signs, please?

That where VERY useful.

Thx :)

**Comment by JavierLeon9966** [comment]
I already added support for fence and stair but the signs I’ll let you to make your own signs because is just a few blocks so I didn’t really bother to add them

**Comment by supercrafter333** [comment]
How can I use stairs,...?

**Comment by JavierLeon9966** [comment]
Add the the corrrect id of the stair and the correct information
