### ISSUE TITLE
How can i fox this ?

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#18]
InvalidArgumentException: "Unmapped ID/metadata combination 526:0" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/convert/ItemTranslator" at line 149

[00:16:17] [Server thread/CRITICAL]: #0 pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream(262): pocketmine\network\mcpe\convert\ItemTranslator->toNetworkId(integer 526, integer 0)

**Comment by ghost** [comment]
I used the config but the acient_debris is not in the Creative menu if i gived me with the /give command internal Server error

**Comment by JavierLeon9966** [comment]
The item form of ancient debris is -271, 526 is the block ID but to get the ID of a item form for a extended block is: 255 - ID

**Comment by DragonfireHD** [comment]
![Uploading PSX_20210402_131343.jpg…]()

**Comment by ghost** [comment]
![PSX_20210402_131343](https://user-images.githubusercontent.com/50929188/113407146-6d79e200-93b5-11eb-9698-e453738cd4eb.jpg)

**Comment by JavierLeon9966** [comment]
First you need to change the `drops` label to -270 not only the `itemId` second don’t overwrite the Netherite Block because is already registered by default

**Comment by ghost** [comment]
Last Question how can i but the block in the Creamenü @JavierLeon9966

**Comment by ghost** [comment]
In the config

**Comment by JavierLeon9966** [comment]
Check the configuration instructions, they are very clear you just need to follow them
