### ISSUE TITLE
What is that ??

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#2]
WHAT is this Plugin ? Can you Explane what this doing ?

**Comment by JavierLeon9966** [comment]
Is a plugin that makes you able to register blocks with 255+ ids

**Comment by JavierLeon9966** [comment]
If you need a real issue, I’ll leave this one open for one day so you can edit it

**Comment by TheBalkanDev** [comment]
How It works?

**Comment by ghost** [comment]
@TheBalkanDev  You must create a plugin to register items and blocks he can not a Config you must code the blocks your self

**Comment by TheBalkanDev** [comment]
And how?

**Comment by JavierLeon9966** [comment]
Well is true, for now you would need a plugin which does register the blocks instead of a config, but I would consider making a config
