### ISSUE TITLE
Slab blocks error

### ISSUE THREAD

**Issue by MrHoller** [JavierLeon9966/ExtendedBlocks#22]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/35010313/113414915-ba19e900-93c6-11eb-949b-bc10255a3bee.gif)

**Comment by JavierLeon9966** [comment]
Show me your configuration

**Comment by MrHoller** [comment]
> Show me your configuration

these are vanilla blocks, when you install your plugin, this bug appears

**Comment by JavierLeon9966** [comment]
Do you tried to register again this slabs or are you using some kind of multi protocol plugin?

**Comment by MrHoller** [comment]
> Вы пытались снова зарегистрировать эти плиты или используете какой-то плагин для нескольких протоколов?

didn't try.

**Comment by MrHoller** [comment]
[ExtendedBlocks.zip](https://github.com/JavierLeon9966/ExtendedBlocks/files/6253375/ExtendedBlocks.zip)

**Comment by JavierLeon9966** [comment]
No, what I meant is do you added them in the configuration, inside a plugin code or are completely vanilla blocks? Because this doesn’t happen to vanilla blocks

**Comment by MrHoller** [comment]
> No, what I meant is do you added them in the configuration, inside a plugin code or are completely vanilla blocks? Because this doesn’t happen to vanilla blocks

Like this https://github.com/MrHoller/ExtendedBlocks

**Comment by JavierLeon9966** [comment]
I don’t see any slab blocks in that fork and the majority of the blocks aren’t using `PlaceholderTrait` which won’t work properly

**Comment by MrHoller** [comment]
> Я не вижу никаких блоков перекрытия в этой вилке, и большинство блоков не используются, и `PlaceholderTrait`они не будут работать должным образом.

where not placeholdertrait i transferred everything from this class to this file

**Comment by UnEnanoMas** [comment]
I have the same error, the slabs if you place them at the top of a block, they become another slab and go down to the bottom

**Comment by JavierLeon9966** [comment]
Fixed in 611b2143658aacfbe8912879cd719fcde52d2c5e
