### ISSUE TITLE
Issues with the config.yml

### ISSUE THREAD

**Issue by TheBalkanDev** [JavierLeon9966/ExtendedBlocks#23]
Hea,

i must say before: NICE Plug-in Dude!

But it have some Problems with the config.yml... or I‘m to stupid for the config.
i don‘t can register other Blocks than the Anchient Debris.

What‘s wrong?
Here the config:
---
"Quartz Bricks": #Required The name of the block
    id: 559 #Required
    hardness: 0.8 #Optional
    toolType: 5 #Optional 0-32 (More info at BlockToolType interface)
    toolHarvestLevel: 5 #Optional 1-6 (1: Wood, 2: Gold, 3: Stone, 4: Iron, 5: Diamond, 6: Netherite)
    drops: [559] #Optional [526, ..] or [[id: 526, meta: 0], ..]
    xpDrops: [0, 0] #Optional
    itemId: -271 #Optional The item form of this block
    variantBitmask: 0 #Optional The meta which the item is allowed
    isReplaceable: false #Optional If the block can be replaced with any other
    breakable: true #Optional If can be broken (Eg: Barrier, Command Block, Bedrock, etc.)
    frictionFactor: 0.6 #Optional How much is the block slippery (Eg: Blue Ice), Note: This won't affect client side
    transparent: false #Optional
    solid: true #Optional
    isFlowable: false #Optional If liquids can destroy this block
    entityCollision: true #Optional If server entities can collide with this block
    passThrough: false #Optional If server entities can pass through this block (Eg: Ladder, Vines, etc.)
    canClimb: false #Optional Note: Doesn't affect client side
    silkTouch: true #Optional If silk touch works with this block
    fuelTime: 0 #Optional How much time in ticks it consumes fuel in a furnace
    flameEncouragement: 0 #Optional Chance of this block getting caught in fire
    flammibility: 0 #Optional Chance of this block burning out
    burnsForever: false #Optional If fire stays forever in this block
    type: 'normal' #Optional normal, stair, trapdoor, wall, fence, fence gate, slab (Won't spawn a double slab, you have to register it)
    creativeItem: true #Optional If this block should appear in the creative menu
...

**Comment by JavierLeon9966** [comment]
The `drops` must also be negative in this case, you need to do 255 - 559: -304 and the `itemId` part must also be -304

**Comment by TheBalkanDev** [comment]
Nope it didn‘t works

---
"Quartz Bricks": #Required The name of the block
    id: 559 #Required
    hardness: 0.8 #Optional
    toolType: 5 #Optional 0-32 (More info at BlockToolType interface)
    toolHarvestLevel: 5 #Optional 1-6 (1: Wood, 2: Gold, 3: Stone, 4: Iron, 5: Diamond, 6: Netherite)
    drops: [255 - 559: -304] #Optional [526, ..] or [[id: 526, meta: 0], ..]
    xpDrops: [0, 0] #Optional
    itemId: -304 #Optional The item form of this block
    variantBitmask: 0 #Optional The meta which the item is allowed
    isReplaceable: false #Optional If the block can be replaced with any other
    breakable: true #Optional If can be broken (Eg: Barrier, Command Block, Bedrock, etc.)
    frictionFactor: 0.6 #Optional How much is the block slippery (Eg: Blue Ice), Note: This won't affect client side
    transparent: false #Optional
    solid: true #Optional
    isFlowable: false #Optional If liquids can destroy this block
    entityCollision: true #Optional If server entities can collide with this block
    passThrough: false #Optional If server entities can pass through this block (Eg: Ladder, Vines, etc.)
    canClimb: false #Optional Note: Doesn't affect client side
    silkTouch: true #Optional If silk touch works with this block
    fuelTime: 0 #Optional How much time in ticks it consumes fuel in a furnace
    flameEncouragement: 0 #Optional Chance of this block getting caught in fire
    flammibility: 0 #Optional Chance of this block burning out
    burnsForever: false #Optional If fire stays forever in this block
    type: 'normal' #Optional normal, stair, trapdoor, wall, fence, fence gate, slab (Won't spawn a double slab, you have to register it)
    creativeItem: true #Optional If this block should appear in the creative menu
...

**Comment by JavierLeon9966** [comment]
Don’t do that, this is how you’re supposed to do it
```yaml
drops: [-304]
```
