### ISSUE TITLE
Need Help for Creative Menü and Placement 

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#24]
![Screenshot_20210403-190147_ES File Explorer](https://user-images.githubusercontent.com/50929188/113484078-240dbd80-94af-11eb-861e-45cd338cb690.png)

The Items and Blocks are in the Creative menü but he can not place 

It is the ExtendedBlocks 

Please Help

**Comment by ghost** [comment]
@JavierLeon9966

**Comment by ghost** [comment]
The Config is nice he place the blocks but the blocks arw not in the Creative Menü if i use this methode the Blocks are implemented in the Menü

**Comment by ghost** [comment]
now i can not place the Block

**Comment by ghost** [comment]
now 
![Screenshot_20210403-190833_Minecraft](https://user-images.githubusercontent.com/50929188/113484255-02f99c80-94b0-11eb-94d9-93baf852009b.png)


Shroomlight 
Basalt
Bell
Netherite from you are now in the Creative menü but i can not place

**Comment by JavierLeon9966** [comment]
Please just create issues about relating to the plugin itself, not invalid ones like being unable to setup correctly the configuration, you need to follow the instructions in the configuration and also I need to be able to understand you

**Comment by JavierLeon9966** [comment]
> ![Screenshot_20210403-190147_ES File Explorer](https://user-images.githubusercontent.com/50929188/113484078-240dbd80-94af-11eb-861e-45cd338cb690.png)
> 
> The Items and Blocks are in the Creative menü but he can not place
> 
> It is the ExtendedBlocks
> 
> Please Help

You need to do `ItemFactory::addCreativeItem` not `ItemFactory::registerItem`

**Comment by ghost** [comment]
@JavierLeon9966 
![Screenshot_20210404-012816_Minecraft](https://user-images.githubusercontent.com/50929188/113493146-9600f980-94e5-11eb-9aa0-1e97d06d2417.png)
![Screenshot_20210404-012827_Minecraft](https://user-images.githubusercontent.com/50929188/113493149-9a2d1700-94e5-11eb-9b36-523b964d0676.png)

![Screenshot_20210404-012845_Minecraft](https://user-images.githubusercontent.com/50929188/113493153-9ef1cb00-94e5-11eb-89d5-bc7daebc7f93.png)

Just Placement

**Comment by ghost** [comment]
I do what you say 

You need to do ItemFactory::addCreativeItem not ItemFactory::registerItem


But all items not more in the creativemenü

**Comment by note3crafter** [comment]
i have the same proplem

**Comment by note3crafter** [comment]
> 
> 
> I do what you say
> 
> You need to do ItemFactory::addCreativeItem not ItemFactory::registerItem
> 
> But all items not more in the creativemenü
Da du ja deutsch eventuell sprichst! Du darfst keine Items hinzufügen die es so ja auch nicht gibt...
https://minecraft.fandom.com/wiki/Bedrock_Edition_data_values

Heißt alles was rot ist darf nicht hinzugefügt werden!
