### ISSUE TITLE
Too many blocks in a chunk.

### ISSUE THREAD

**Issue by mentagess** [JavierLeon9966/ExtendedBlocks#33]
Hello an error occurred due to too large a quantity of block with an id greater than 255 in a single one is even chunck I would like to have an answer and not a closure of this issue.
![IMG_20210417_143544](https://user-images.githubusercontent.com/54176064/115142058-f2b0f800-a03f-11eb-95c6-310251f33dd6.jpg)

**Comment by JavierLeon9966** [comment]
This is fixed in commit 27b58eb, just wait until I update it into Poggit

**Comment by JavierLeon9966** [comment]
Closing this issue. If you have any glitches or errors in this plugin, feel free to open an issue.
