### ISSUE TITLE
[BUG:] A lot of Items wheren't added to the Inventory in PM 3.19.1

### ISSUE THREAD

**Issue by supercrafter333** [JavierLeon9966/ExtendedBlocks#35]
I've updated my server to PM 3.19.1 for the Inventory fixes, but I've seen that many Items that I have added to the creative Inentory are no longer in the crea Inventory.

Please fix this fast, that's bad.

You make a great Job!

**Comment by supercrafter333** [comment]
```php
//My Code:
//Cryingobsidian (-289)
        $cryingobsidian = new cryingobsidian(0);
        BlockFactory::registerBlock($cryingobsidian, true);
        ItemFactory::registerItem(new ItemBlock($cryingobsidian->getId(), 0, 255 - $cryingobsidian->getId()), true);
        ItemFactory::addCreativeItem(ItemFactory::get(255 - $cryingobsidian->getId()));
```

**Comment by supercrafter333** [comment]
I can't see the Item anywhere in the Inventory

**Comment by JavierLeon9966** [comment]
Is not my fault that’s not in the creative inventory, must be something within PMMP

**Comment by supercrafter333** [comment]
Okay, with getName() function that will work
