### ISSUE TITLE
Item frame is affected

### ISSUE THREAD

**Issue by UnEnanoMas** [JavierLeon9966/ExtendedBlocks#36]
![image](https://user-images.githubusercontent.com/63286108/116240770-7f586600-a764-11eb-9ccf-d92eae2472b3.png)

**Comment by supercrafter333** [comment]
Thats right.

**Comment by JavierLeon9966** [comment]
This would need more testing if this issue ocurrs using ExtendedBlocks

**Comment by UnEnanoMas** [comment]
If you remove the ExtendedBlocks plugin it works perfectly, then yes, this plugin causes it

**Comment by supercrafter333** [comment]
I've tested it too and that's right. ExtendedBlocks caused it.

**Comment by supercrafter333** [comment]
Please fix it fast!! It's a very bad bug!!!

**Comment by Azvyl** [comment]
The same problem with Upper wooden slabs (#22)

I'm sure the bug was caused by https://github.com/JavierLeon9966/ExtendedBlocks/blob/stable/src/JavierLeon9966/ExtendedBlocks/Main.php#L33

**Comment by supercrafter333** [comment]
Outsch, that's bad

**Comment by JavierLeon9966** [comment]
Hmm, maybe that causes the problem. But atleast is a visual glitch and don’t affect anything related to your worlds right?

**Comment by Azvyl** [comment]
> Hmm, maybe that causes the problem. But atleast is a visual glitch and don’t affect anything related to your worlds right?

but it will be confusing 😆

> Please fix it fast!! It's a very bad bug!!!

I think I fixed it with this yesterday:
```php
if ($legacyId <= 469) {
    continue;
}
```
I added it to [this](https://github.com/JavierLeon9966/ExtendedBlocks/blob/stable/src/JavierLeon9966/ExtendedBlocks/Main.php#L44) line

**Comment by supercrafter333** [comment]
Replaced or added?

**Comment by Azvyl** [comment]
> Replaced or added?

```php
$legacyId = $nameToLegacyMap[$name];
if ($legacyId <= 469) {
    continue;
}
if(!isset($metaMap[$legacyId])){
	$metaMap[$legacyId] = 0;
}
```

**Comment by supercrafter333** [comment]
That doesn't fix the problem.

**Comment by UnEnanoMas** [comment]
This should fix Javier, since it is his code and he will know that he has put it wrong xd

**Comment by Azvyl** [comment]
> That doesn't fix the problem.

but it solved my problem \

https://youtu.be/LVWlXplJDH0

**Comment by supercrafter333** [comment]
I think that you don't understand the problem.

**Comment by UnEnanoMas** [comment]
Well in the video it works well lol

**Comment by supercrafter333** [comment]
The item frame is wrongly placed after you have re-entered the respective world.

**Comment by UnEnanoMas** [comment]
Send video of that @DavyCraft648

**Comment by Azvyl** [comment]
> The item frame is wrongly placed after you have re-entered the respective world.

> Send video of that

this? https://youtu.be/g89e_WbkPIA

**Comment by UnEnanoMas** [comment]
@JavierLeon9966 it seems they have fixed it

**Comment by JavierLeon9966** [comment]
> @JavierLeon9966 it seems they have fixed it

Ok, I’ll try that

**Comment by JavierLeon9966** [comment]
> > Replaced or added?
> 
> ```
> $legacyId = $nameToLegacyMap[$name];
> if ($legacyId <= 469) {
>     continue;
> }
> if(!isset($metaMap[$legacyId])){
> 	$metaMap[$legacyId] = 0;
> }
> ```

Confirmed, this code fixes the rendering problem

**Comment by JavierLeon9966** [comment]
Commit ab0233c fixes this problem
