### ISSUE TITLE
ExtendedBlock Compatibility with other plugin

### ISSUE THREAD

**Issue by Blackjack200** [JavierLeon9966/ExtendedBlocks#39]
customize:
AxisAlignedBB
canClimb
canPassThrough
hasEntityCollision
canBeFlowedInto
isSolid
isTransparent
getFrictionFactor
getHardness

**Comment by JavierLeon9966** [comment]
AxisAlignedBB Customizable by code
canClimb Customizable by config.yml
canPassThrough Customizable by config.yml
hasEntityCollision Customizable by config.yml
canBeFlowedInto Customizable by config.yml
isSolid Customizable by config.yml
isTransparent Customizable by config.yml
getFrictionFactor Customizable by config.yml
getHardness Customizable by config.yml
