### ISSUE TITLE
How I can register Blocks?

### ISSUE THREAD

**Issue by TheBalkanDev** [JavierLeon9966/ExtendedBlocks#4]
Good Morning everyone,

How I can register Blocks?

And Can I only register Blocks with an ID that is higher than 256?

For the Author: Plz add an Description.

**Comment by TheBalkanDev** [comment]
And can I add 1.14 Blocks like lanterns?

**Comment by JavierLeon9966** [comment]
The purpose of this plugin is that supports to register blocks ID above 255, so you can register 0-255 normally in PocketMine.
In order to register those blocks you would need the block info like ID and default meta.

**Comment by JavierLeon9966** [comment]
I added more information in the description so you can guide with it.
