### ISSUE TITLE
[BUG:] No birch fences

### ISSUE THREAD

**Issue by supercrafter333** [JavierLeon9966/ExtendedBlocks#40]
With ExtendedBlocks on a server, birch fences aren't in the creative inventory.

**Comment by JavierLeon9966** [comment]
You need to add them in `config.yml`

**Comment by supercrafter333** [comment]
Wtf nooo!!!!! Pocketmine already have birch fences but with ExtendedBlock there aren't in the inventory

**Comment by JavierLeon9966** [comment]
I still see birch fence @supercrafter333 
![7CCD971D-BAAB-4092-A4F4-31525E50303D](https://user-images.githubusercontent.com/58715544/118058034-9a7dc500-b363-11eb-9fc9-4ec6c6f1864a.png)
