### ISSUE TITLE
Blocks revert to block ID 255

### ISSUE THREAD

**Issue by UnEnanoMas** [JavierLeon9966/ExtendedBlocks#41]
When you try to use a block with a negative ID, you put it in and then break it, the objects around it become the ID 255

https://streamable.com/3xycza

Dev 45
PHP 7.4
(Oficial Pocketmine Phar and Console)

**Comment by JavierLeon9966** [comment]
Unable to reproduce, you might have done something wrong 

https://user-images.githubusercontent.com/58715544/118536802-8864a380-b722-11eb-908e-3bf731a9e29a.mov

**Comment by UnEnanoMas** [comment]
https://poggit.pmmp.io/p/AntiXray/1.0.1

The plugin that was causing the error

I put it in case the same thing happens to someone
