### ISSUE TITLE
ExtendedBlocks Server Crash

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#42]
DG-Blocks = ExtendedBlocks

Too many packets in a single batch
File: pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket
Line: 101
Type: UnexpectedValueException

#0 plugins/DG-Blocks.3.9.0.phar/src/JavierLeon9966/ExtendedBlocks/Main(331): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
#1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): JavierLeon9966\ExtendedBlocks\Main->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent)
#2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object JavierLeon9966\ExtendedBlocks\Main, object pocketmine\event\server\DataPacketSendEvent)
#3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent)
#4 pmsrc/src/pocketmine/Player(3354): pocketmine\event\Event->call()
#5 pmsrc/src/pocketmine/Server(1761): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket, boolean , boolean )
#6 pmsrc/src/pocketmine/Server(1743): pocketmine\Server->broadcastPacketsCallback(object pocketmine\network\mcpe\protocol\BatchPacket, array[1], boolean )
#7 pmsrc/src/pocketmine/level/Level(1024): pocketmine\Server->batchPackets(array[1], array[1200], boolean , boolean )
#8 plugins/DG-Blocks.3.9.0.phar/src/JavierLeon9966/ExtendedBlocks/Main(344): pocketmine\level\Level->sendBlocks(array[1], array[1200], integer 11)
#9 pmsrc/src/pocketmine/scheduler/ClosureTask(61): JavierLeon9966\ExtendedBlocks\Main::JavierLeon9966\ExtendedBlocks\{closure}(integer 160801)
#10 pmsrc/src/pocketmine/scheduler/TaskHandler(137): pocketmine\scheduler\ClosureTask->onRun(integer 160801)
#11 pmsrc/src/pocketmine/scheduler/TaskScheduler(179): pocketmine\scheduler\TaskHandler->run(integer 160801)
#12 pmsrc/src/pocketmine/plugin/PluginManager(654): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 160801)
#13 pmsrc/src/pocketmine/Server(2389): pocketmine\plugin\PluginManager->tickSchedulers(integer 160801)
#14 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
#15 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
#16 pmsrc/src/pocketmine/Server(1586

**Comment by ghost** [comment]
Line 331 = 

	`public function onDataPacketSend(DataPacketSendEvent $event): void{
		$packet = $event->getPacket();
		$player = $event->getPlayer();
		$level = $player->getLevel();
		if($packet instanceof BatchPacket){
			$blocks = [];
			$packet->decode();
			 Here Beginns 331>>>> foreach($packet->getPackets() as $buf){`

**Comment by Azvyl** [comment]
use the latest version
