### ISSUE TITLE
ExtendedBlocks bug with different blocks

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#43]
![Screenshot_20210528-192434_Minecraft](https://user-images.githubusercontent.com/50929188/120853986-24950400-c585-11eb-84d6-59504b7daa55.jpg)
![Screenshot_20210528-192614_Minecraft](https://user-images.githubusercontent.com/50929188/120854019-2eb70280-c585-11eb-95a1-2b4bff5a3a65.jpg)

https://user-images.githubusercontent.com/50929188/120854408-cd436380-c585-11eb-938b-31661d515eec.mov

**Comment by DragonfireHD** [comment]
Uploading video0-2.mov…

**Comment by ghost** [comment]
https://user-images.githubusercontent.com/50929188/120854578-08459700-c586-11eb-868f-78557c40c04f.mov

**Comment by Azvyl** [comment]
agan, use the latest version

it was fixed on 1.1.3
