### ISSUE TITLE
SERVER crashed for this problem

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#44]
Error: Too many packets in a single batch
File: pmsrc/src/pocketmine/network/mcpe/protocol/BatchPacket
Line: 101
Type: UnexpectedValueException

A PLUGIN WAS INVOLVED IN THIS CRASH
BAD PLUGIN: DG-Blocks v3.8.0

Code:

Backtrace:
#0 plugins/DG-Blocks.3.9.0.phar/src/JavierLeon9966/ExtendedBlocks/Main(331): pocketmine\network\mcpe\protocol\BatchPacket->getPackets()
#1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): JavierLeon9966\ExtendedBlocks\Main->onDataPacketSend(object pocketmine\event\server\DataPacketSendEvent)
#2 `
pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object JavierLeon9966\ExtendedBlocks\Main, object pocketmine\event\server\DataPacketSendEvent)
#3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketSendEvent)
#4 pmsrc/src/pocketmine/Player(3356): pocketmine\event\Event->call()
#5 pmsrc/src/pocketmine/Server(1761): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\BatchPacket, boolean , boolean )
#6 pmsrc/src/pocketmine/Server(1743): pocketmine\Server->broadcastPacketsCallback(object pocketmine\network\mcpe\protocol\BatchPacket, array[1], boolean )
#7 pmsrc/src/pocketmine/level/Level(923): pocketmine\Server->batchPackets(array[1], array[2072], boolean , boolean )
#8 pmsrc/src/pocketmine/level/Level(787): pocketmine\level\Level->actuallyDoTick(integer 5367)
#9 pmsrc/src/pocketmine/Server(2265): pocketmine\level\Level->doTick(integer 5367)
#10 pmsrc/src/pocketmine/Server(2396): pocketmine\Server->checkTickUpdates(integer 5367, double 1623437020.1214)
#11 pmsrc/src/pocketmine/Server(2152): pocketmine\Server->tick()
#12 pmsrc/src/pocketmine/Server(1992): pocketmine\Server->tickProcessor()
#13 pmsrc/src/pocketmine/Server(1586): pocketmine\Server->start()
#14 pmsrc/src/pocketmine/PocketMine(291): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[16] /home/minecraft/, string[24] /home/minecraft/plugins/)
#15 pmsrc/src/pocketmine/PocketMine(321): pocketmine\server()
#16 pmsrc(11): require(string[68] phar:///home/minecraft/pocketmine.phar/src/pocketmine/PocketMine.php)`

**PocketMine-MP version: 3.20.0 [Protocol 440]
Git commit: 99964709c932089189f921f62c6474a67fb94c9c
uname -a: Linux 39fbfa08ce36 5.7.0-0.bpo.2-amd64 #1 SMP Debian 5.7.10-1~bpo10+1 (2020-07-30) x86_64
PHP Version: 7.4.13
Zend version: 3.4.0
OS : Linux, linux**

```
	 * @priority MONITOR
	 * @ignoreCancelled true
	 */
	public function onDataPacketSend(DataPacketSendEvent $event): void{
		$packet = $event->getPacket();
		$player = $event->getPlayer();
		$level = $player->getLevel();
		if($packet instanceof BatchPacket){
			$blocks = [];
			$packet->decode();
			foreach($packet->getPackets() as $buf){
```

Pls help worlds crashed

**Comment by JavierLeon9966** [comment]
You are using an outdated version
