### ISSUE TITLE
Items or Blocks are not in the Right Position 

### ISSUE THREAD

**Issue by ghost** [JavierLeon9966/ExtendedBlocks#55]
![Screenshot_20211208-010347_Minecraft](https://user-images.githubusercontent.com/50929188/145125106-4e9bee67-a569-43c1-ab6a-379f4d4fddd1.png)

Items and Blocks are not in the Right Position 

Wood logs dosent displayed anymore 
And he gives more plus Slots  have you a idea why he do that?

**Comment by JavierLeon9966** [comment]
1. It seems to be in the right position for me according to that screenshot
2. Go blame PocketMine-MP, the order is based on there and ExtendedBlocks adds it in the exact slot
