### ISSUE TITLE
Block direct replace to air

### ISSUE THREAD

**Issue by tunikakeks** [JavierLeon9966/ExtendedBlocks#7]
The block got replaced directly to air.

@JavierLeon9966 

My Block.php:

  ```<?php
namespace KeksDev\MoreBlocks\block;

use pocketmine\entity\Entity;
use pocketmine\Player;
use pocketmine\block\Block;
use pocketmine\item\Item;
use pocketmine\math\Vector3;
use JavierLeon9966\ExtendedBlocks\block\PlaceholderTrait;

class LagerFeuer extends Block{
	
	use PlaceholderTrait;

	protected $id = 464;

	public function __construct(int $meta = 0){
		$this->meta = $meta;
		$this->itemId = 720;
	}

	public function getName() : string{
		return "campfire";
	}

	public function isSolid() : bool{
		return true;
	}
	
	public function getLightLevel() : int{
		return 15;
	}

	public function getHardness() : float{
		return 10;
	}
	
	public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null) : bool {
		$this->getLevel()->setBlock($this, $this, true, true);
	}

	
}```

**Comment by JavierLeon9966** [comment]
Don’t use the method
```php
public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null): bool;
```
In this case is not necessary to use it unless you implement a oriented block then you would need to parent the method so is able to be placed correctly.

**Comment by efor89** [comment]
i have the same problem
```
<?php

namespace efor89\block;

use JavierLeon9966\ExtendedBlocks\block\PlaceholderTrait;
use pocketmine\block\BlockToolType;
use JavierLeon9966\ExtendedBlocks\block\Placeholder;

class Seelenlagerfeuer extends Placeholder{

    public $id = 545;

    public function __construct(int $meta = 0){
        $this->meta = $meta;
    }

    public function getName() : string{
        return "Soul campfire";
    }

    public function getHardness() : float{
        return 1;
    }

    public function getLightLevel() : int{
        return 10;
    }

    public function getToolType() : int{
        return BlockToolType::TYPE_AXE;
    }
}```

**Comment by xxAROX** [comment]
> 
> 
> i have the same problem
> 
> ```
> <?php
> 
> namespace efor89\block;
> 
> use JavierLeon9966\ExtendedBlocks\block\PlaceholderTrait;
> use pocketmine\block\BlockToolType;
> use JavierLeon9966\ExtendedBlocks\block\Placeholder;
> 
> class Seelenlagerfeuer extends Placeholder{
> 
>     public $id = 545;
> 
>     public function __construct(int $meta = 0){
>         $this->meta = $meta;
>     }
> 
>     public function getName() : string{
>         return "Soul campfire";
>     }
> 
>     public function getHardness() : float{
>         return 1;
>     }
> 
>     public function getLightLevel() : int{
>         return 10;
>     }
> 
>     public function getToolType() : int{
>         return BlockToolType::TYPE_AXE;
>     }
> }```
> ```

extends **Block** look example

**Comment by efor89** [comment]
nothing change with class Seelenlagerfeuer extends Block{    if i use //replace ,block is air

**Comment by efor89** [comment]
can you make an example block plz?

**Comment by xxAROX** [comment]
[HERE](https://github.com/JavierLeon9966/ExtendedBlocks#my-block-changes-to-another-one)

**Comment by efor89** [comment]
block is air with //replace


```<?php

namespace efor89\block;

use JavierLeon9966\ExtendedBlocks\block\PlaceholderTrait;
use JavierLeon9966\ExtendedBlocks\block\Placeholder;

class Soulcampfire extends Block{
	
	use PlaceholderTrait;

    public $id = 545;

    public function __construct(int $meta = 0){
        $this->meta = $meta;
    }

}```

**Comment by xxAROX** [comment]
i think any kind of worldedit doen't support that

**Comment by efor89** [comment]
mhhh but how i can then place the block?

**Comment by xxAROX** [comment]
you have to do create issue on your kind of worldedit and ask for support for [ExtendedBlocks](https://github.com/JavierLeon9966/ExtendedBlocks)

**Comment by efor89** [comment]
this give an error

Unmapped ID/metadata combination 545:0" (EXCEPTION) in "src/pocketmine/network/mcpe/convert/ItemTranslator" at line 149

**Comment by efor89** [comment]
i try it with costumitemloader then i have the item but without texture and i cant place it

**Comment by xxAROX** [comment]
> 
> 
> i try it with costumitemloader then i have the item but without texture and i cant place it

i got the same error, okay but thats off-topic

**Comment by JavierLeon9966** [comment]
To get the item form you need to 255 - blockID and yes WorldEdit currently doesn’t support this. @efor89

**Comment by tunikakeks** [comment]
> Don’t use the method
> 
> ```
> public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null): bool;
> ```
> 
> In this case is not necessary to use it unless you implement a oriented block then you would need to parent the method so is able to be placed correctly.

Also dont work

**Comment by xxAROX** [comment]
@JavierLeon9966 do you have a block id list with all 1.16 blocks?

**Comment by tunikakeks** [comment]
> @JavierLeon9966 do you have a block id list with all 1.16 blocks?

https://minecraft.gamepedia.com/Bedrock_Edition_data_values#Block_IDs

**Comment by xxAROX** [comment]
thank you soo much

**Comment by ghost** [comment]
Here is the Official Fullscreen in HD Item and Block Ids for 1.16

https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/c6/DataValuesPE.png/revision/latest?cb=20200130075041&format=original

**Comment by tunikakeks** [comment]
I still need help btw

**Comment by tunikakeks** [comment]
@JavierLeon9966 do you have any other ideas why it dont works

**Comment by xxAROX** [comment]
@tunikakeks try hardcode

**Comment by JavierLeon9966** [comment]
> > Don’t use the method
> > ```
> > public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null): bool;
> > ```
> > 
> > 
> > In this case is not necessary to use it unless you implement a oriented block then you would need to parent the method so is able to be placed correctly.
> 
> Also dont work

Lemme see your code

**Comment by xxAROX** [comment]
You cant replace blocks with extended blocks

> 
> 
> nothing change with class Seelenlagerfeuer extends Block{ if i use //replace ,block is air

**Comment by xxAROX** [comment]
```php
static function testing(Player $player, LevelChunkPacket $pk): void{
                    $pk->decode();
                    $this->getScheduler()->scheduleDelayedTask(new ClosureTask(static function() use($pk, $player, $level): void{
                        $blocks = [];
                        //TODO: insert Placeholder's, dont forget Placeholder::position(Vector3)
                        if(count($blocks) > 0){
                            $level->sendBlocks([$player], $blocks, UpdateBlockPacket::FLAG_ALL_PRIORITY);
                        }
                    }), intdiv($player->getPing(), 50) +1);
                }
            }
}
```
it should work, if not then try another method.

**Comment by xxAROX** [comment]
[List of all Block Ids ported to PHP class](https://gist.github.com/xxAROX/4abab8f5bc75a23b5ddc2df4f36b0483)

**Comment by JavierLeon9966** [comment]
> You cant replace blocks with extended blocks
> 
> > nothing change with class Seelenlagerfeuer extends Block{ if i use //replace ,block is air

This plugin doesn’t support WorldEdit for now, so that’s why is replaced with air or another block

**Comment by JavierLeon9966** [comment]
BuilderTools or BlockSnipers aren’t supported in this plugin, so that’s it gets replaced with air the most time, so if you have any issues regarding of my plugin and not outside you can create another issue.

**Comment by tunikakeks** [comment]
> > > Don’t use the method
> > > ```
> > > public function place(Item $item, Block $blockReplace, Block $blockClicked, int $face, Vector3 $clickVector, Player $player = null): bool;
> > > ```
> > > 
> > > 
> > > In this case is not necessary to use it unless you implement a oriented block then you would need to parent the method so is able to be placed correctly.
> > 
> > 
> > Also dont work
> 
> Lemme see your code

```<?php
namespace JavierLeon9966\ExtendedBlocks\block;

use pocketmine\entity\Entity;
use pocketmine\Player;
use pocketmine\block\Solid;
use pocketmine\item\Item;
use pocketmine\math\Vector3;
use JavierLeon9966\ExtendedBlocks\block\PlaceholderTrait;

class LagerFeuer extends Solid{
  
  use PlaceholderTrait;

  protected $id = 464;

  public function __construct(int $meta = 0){
  	$this->meta = $meta;
  	$this->itemId = 720;
  }

  public function getName() : string{
  	return "campfire";
  }

  public function isSolid() : bool{
  	return true;
  }
  
  public function getLightLevel() : int{
  	return 15;
  }

  public function getHardness() : float{
  	return 10;
  }
  
  
}```
